### ISSUE TITLE
gspread credentials refresh failing

### ISSUE THREAD

**Issue by KyleBrownCS** [KyleBrownCS/-r-winnipegjets-scripts#10]
Credentials are expiring for google drive auth. Here is an example traceback. All instances of issue result in the 401 Error

```Traceback (most recent call last):
File "/home/kyle/-r-winnipegjets-scripts/drive_manager.py", line 280, in get_sheet_single_column
spreadsheet = self.gc.open_by_key(file_id)
File "/home/kyle/gspread/gspread/client.py", line 105, in open_by_key
feed = self.get_spreadsheets_feed()
File "/home/kyle/gspread/gspread/client.py", line 155, in get_spreadsheets_feed
 r = self.session.get(url)
File "/home/kyle/gspread/gspread/httpsession.py", line 73, in get
return self.request('GET', url, params=params, **kwargs)
File "/home/kyle/gspread/gspread/httpsession.py", line 69, in request
response.status_code, response.content))
gspread.exceptions.RequestError: (401, '401: b\'<HTML>\\n<HEAD>\\n<TITLE>Token invalid - Invalid token: Token expired.<
/TITLE>\\n</HEAD>\\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\\n<H1>Token invalid - Invalid token: Token expired.</H1>\\n<H2>Error 401</H2>\\n</BODY>\\n</HTML>\\n\'')
gwg_updater.service: main process exited, code=exited, status=255/n/a
```

This bug is preventing the GWG from being posted automatically on game days early in the morning

**Comment by KyleBrownCS** [comment]
Fixed in 090781cefeefdfb25c9fb5c9f430e98f88314fb1
